export const app_data = {
	"a2048": {
		module: window.a2048_module,
		title: "2048",
		description: "Slide the tiles (swiping, arrow keys, or wasd keys) and combine like numbers with each other. Try to beat your personal best score.",
		url: "https://github.com/uplinkx/2048",
		aspect_ratio: 1/1,
		console: false,
	},
	"chess": {
		module: window.chess_module,
		title: "Chess",
		description: "Small game of chess. Click on pieces and move them around",
		url: "https://github.com/uplinkx/chess",
		aspect_ratio: 1/1,
		console: false,
	},
	"flappy_bird": {
		module: window.flappy_bird_module,
		title: "Flappy Bird",
		description: "Recreation of flappy bird. Tap on the game to make flappy bird jump. Increase your score as you jump over pipes, how far will you go?",
		url: "https://github.com/uplinkx/flappy_bird",
		aspect_ratio: 1/1,
		console: false,
	},
	"mympheus": {
		module: window.mympheus_module,
		title: "Mympheus",
		description: "Demo of a mobile game.",
		url: "https://github.com/uplinkx/2048",
		aspect_ratio: 1008 / 2000,
		console: false,
	},
	"pacman": {
		module: window.pacman_module,
		title: "Pacman",
		description: "Swipe on the screen to mov Pacman or use arrows (or wasd) to move Pacman.",
		url: "https://github.com/uplinkx/pacman",
		aspect_ratio: 224/288,
		console: false,
	},
	"tic_tac_toe": {
		module: window.tic_tac_toe_module,
		title: "Tic-Tac-Toe",
		description: "Face off against a min-max AI in this simple game of tic-tac-toe. Press R to restart the game and try again.",
		url: "https://github.com/uplinkx/tic_tac_toe",
		aspect_ratio: 1/1,
		console: false,
	},
}
